# Generated by Django 4.1.3 on 2022-12-03 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Po_line_item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_item_id', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('type_quantity', models.CharField(max_length=256)),
                ('sub_type', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('unit_line_price_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
