# Generated by Django 4.1.3 on 2022-12-03 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand_PO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_po_number', models.CharField(max_length=256)),
                ('po_date', models.DateField()),
                ('supplier_number', models.CharField(blank=True, max_length=256)),
                ('payment_term', models.TextField(blank=True)),
                ('shipping_term', models.TextField(blank=True)),
                ('mailing_address', models.CharField(blank=True, max_length=256)),
                ('hsn', models.CharField(max_length=256)),
                ('name_of_certificate', models.CharField(max_length=256)),
                ('upload_pdf_to_po', models.ImageField(upload_to='media')),
                ('updated_by', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brand_app.brand')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brand_app.document')),
            ],
        ),
    ]
